service: safehaven-backend

frameworkVersion: '3'

# Package optimization - comprehensive dependency inclusion
package:
  patterns:
    - '!src/**'          # Exclude TypeScript source
    - '!.serverless/**'  # Exclude serverless temp files
    - '!*.test.*'        # Exclude test files
    - '!jest.config.*'   # Exclude Jest config
    - '!tsconfig.json'   # Exclude TypeScript config
    - '!webpack.config.js' # Exclude webpack config
    - '!README.md'       # Exclude documentation
    - '!node_modules/@types/**'  # Exclude TypeScript types
    - '!node_modules/**/*.d.ts'  # Exclude type definition files
    - '!node_modules/**/test/**' # Exclude test directories
    - '!node_modules/**'         # Exclude all node_modules first
    - '../node_modules/@aws-sdk/**'     # Include AWS SDK v3
    - '../node_modules/@smithy/**'      # Include Smithy dependencies
    - '../node_modules/@aws/**'         # Include @aws scoped packages
    - '../node_modules/uuid/**'         # Include UUID
    - '../node_modules/bcryptjs/**'     # Include bcrypt
    - '../node_modules/joi/**'          # Include Joi validation
    - '../node_modules/jsonwebtoken/**' # Include JWT
    - '../node_modules/jws/**'          # Include JWS
    - '../node_modules/ms/**'           # Include ms time parsing
    - '../node_modules/mnemonist/**'    # Include mnemonist
    - '../node_modules/obliterator/**'  # Include obliterator
    - '../node_modules/tslib/**'        # Include TypeScript runtime
    - '../node_modules/fast-xml-parser/**' # Include XML parser
    - '../node_modules/safe-buffer/**'  # Include safe buffer
    - '../node_modules/jwa/**'          # Include JSON Web Algorithm
    - '../node_modules/ecdsa-sig-formatter/**' # Include ECDSA signature formatter
    - '../node_modules/lodash.includes/**' # Include lodash includes utility
    - '../node_modules/lodash.isboolean/**' # Include lodash isboolean utility
    - '../node_modules/lodash.isinteger/**' # Include lodash isinteger utility
    - '../node_modules/lodash.isnumber/**'  # Include lodash isnumber utility
    - '../node_modules/lodash.isstring/**'  # Include lodash isstring utility
    - '../node_modules/lodash.isplainobject/**' # Include lodash isplainobject utility
    - '../node_modules/lodash.once/**'      # Include lodash once utility
    - '!node_modules/**/tests/**' # Exclude tests directories
    - '!node_modules/**/*.test.js' # Exclude test files
    - 'dist/**'          # Include compiled JavaScript
    # Include essential AWS SDK and auth dependencies from root node_modules
    - '../node_modules/@aws-sdk/**'
    - '../node_modules/@smithy/**'
    - '../node_modules/@aws/**'
    - '../node_modules/uuid/**'
    - '../node_modules/bcryptjs/**'
    - '../node_modules/joi/**'
    - '../node_modules/jsonwebtoken/**'
    - '../node_modules/jws/**'
    - '../node_modules/ms/**'
    - '../node_modules/mnemonist/**'
    - '../node_modules/obliterator/**'
    - '../node_modules/tslib/**'
    - '../node_modules/aws-sdk/**'
    - '../node_modules/jmespath/**'
    - '../node_modules/xml2js/**'
    - '../node_modules/querystring/**'
    - '../node_modules/querystringify/**'
    - '../node_modules/buffer/**'
    - '../node_modules/events/**'
    - '../node_modules/stream-browserify/**'
    - '../node_modules/util/**'
    - '../node_modules/crypto-browserify/**'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    SHELTERS_TABLE: ${self:service}-shelters-${self:provider.stage}
    USERS_TABLE: ${self:service}-users-${self:provider.stage}
    ALERTS_TABLE: ${self:service}-alerts-${self:provider.stage}
    CONNECTIONS_TABLE: ${self:service}-connections-${self:provider.stage}
    SHELTER_UPDATES_TOPIC: ${self:service}-shelter-updates-${self:provider.stage}
    AWS_LOCATION_MAP_NAME: ${self:service}-map-${self:provider.stage}
    AWS_LOCATION_PLACE_INDEX: ${self:service}-places-${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET, 'hackathon-jwt-secret-change-in-production'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SHELTERS_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ALERTS_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CONNECTIONS_TABLE}"
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
        - sns:Unsubscribe
      Resource:
        - "arn:aws:sns:${self:provider.region}:*:${self:provider.environment.SHELTER_UPDATES_TOPIC}"
    - Effect: Allow
      Action:
        - geo:GetMap*
        - geo:SearchPlaceIndex*
        - geo:CalculateRoute*
        - geo:BatchGetGeofence*
      Resource:
        - "arn:aws:geo:${self:provider.region}:*:map/${self:provider.environment.AWS_LOCATION_MAP_NAME}"
        - "arn:aws:geo:${self:provider.region}:*:place-index/${self:provider.environment.AWS_LOCATION_PLACE_INDEX}"
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource:
        - "arn:aws:execute-api:${self:provider.region}:*:*/@connections/*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3010
    websocketPort: 3011

functions:
  # Test Functions
  simpleTest:
    handler: dist/functions/test/simple.handler
    events:
      - http:
          path: test/simple
          method: get
          cors: true

  testRegister:
    handler: dist/functions/test/register-simple.handler
    events:
      - http:
          path: test/register
          method: post
          cors: true

  testDynamoDB:
    handler: dist/functions/test/dynamodb-test.handler
    events:
      - http:
          path: test/dynamodb
          method: get
          cors: true

  testDynamoDBv2:
    handler: dist/functions/test/dynamodb-v2-test.handler
    events:
      - http:
          path: test/dynamodb-v2
          method: get
          cors: true

  # Authentication Functions
  authLogin:
    handler: dist/functions/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  authRegister:
    handler: dist/functions/auth/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  # Shelter Management Functions
  createShelter:
    handler: dist/functions/shelters/create.handler
    events:
      - http:
          path: shelters
          method: post
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  getShelters:
    handler: dist/functions/shelters/list.handler
    events:
      - http:
          path: shelters
          method: get
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  getShelter:
    handler: dist/functions/shelters/get.handler
    events:
      - http:
          path: shelters/{shelterId}
          method: get
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  updateShelterStatus:
    handler: dist/functions/shelters/updateStatus.handler
    events:
      - http:
          path: shelters/{shelterId}/status
          method: put
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  # Location Service Functions
  searchPlaces:
    handler: dist/functions/location/searchPlaces.handler
    events:
      - http:
          path: location/search
          method: post
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  getMapStyle:
    handler: dist/functions/location/getMapStyle.handler
    events:
      - http:
          path: location/mapstyle
          method: get
          cors: true

  # Alert Management Functions
  createAlert:
    handler: dist/functions/alerts/create.handler
    events:
      - http:
          path: alerts
          method: post
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  getAlerts:
    handler: dist/functions/alerts/list.handler
    events:
      - http:
          path: alerts
          method: get
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  acknowledgeAlert:
    handler: dist/functions/alerts/acknowledge.handler
    events:
      - http:
          path: alerts/{id}/acknowledge
          method: put
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  resolveAlert:
    handler: dist/functions/alerts/resolve.handler
    events:
      - http:
          path: alerts/{id}/resolve
          method: put
          cors: true
          authorizer:
            name: authVerify
            resultTtlInSeconds: 300

  # WebSocket Functions for Real-time Updates
  websocketConnect:
    handler: dist/functions/websocket/connect.handler
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: dist/functions/websocket/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  websocketDefault:
    handler: dist/functions/websocket/default.handler
    events:
      - websocket:
          route: $default

  # Authorization Function
  authVerify:
    handler: dist/functions/auth/verify.handler

resources:
  Resources:
    # DynamoDB Tables
    SheltersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SHELTERS_TABLE}
        AttributeDefinitions:
          - AttributeName: shelterId
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: shelterId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StatusIndex
            KeySchema:
              - AttributeName: status
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    AlertsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ALERTS_TABLE}
        AttributeDefinitions:
          - AttributeName: alertId
            AttributeType: S
          - AttributeName: shelterId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: alertId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: shelterId-timestamp-index
            KeySchema:
              - AttributeName: shelterId
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CONNECTIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    # SNS Topic for Shelter Updates
    ShelterUpdatesTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.environment.SHELTER_UPDATES_TOPIC}

    # AWS Location Service Map
    LocationMap:
      Type: AWS::Location::Map
      Properties:
        MapName: ${self:provider.environment.AWS_LOCATION_MAP_NAME}
        Configuration:
          Style: VectorEsriStreets
        Description: "SafeHaven emergency shelter mapping"
        PricingPlan: RequestBasedUsage

    # AWS Location Service Place Index
    PlaceIndex:
      Type: AWS::Location::PlaceIndex
      Properties:
        IndexName: ${self:provider.environment.AWS_LOCATION_PLACE_INDEX}
        DataSource: Esri
        Description: "SafeHaven place search and geocoding"
        PricingPlan: RequestBasedUsage

  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:service}-${self:provider.stage}-api-id

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:service}-${self:provider.stage}-root-resource-id

    ShelterUpdatesTopicArn:
      Value:
        Ref: ShelterUpdatesTopic
      Export:
        Name: ${self:service}-${self:provider.stage}-shelter-updates-topic-arn